import { CityTouristicData } from '@/@types/city-touristic-data';
import { CitiesENUM, getCityImage } from '@/utils/get-city-image';

// TODO: implementar a recuperação de mais de uma foto via getCityImage()
const defaultData: CityTouristicData = {
	id: -1,
	name: 'default',
	images: [
		{ ...getCityImage('default', 0) },
		{ ...getCityImage('default', 1) },
		{ ...getCityImage('default', 2) },
	],
	companiesData: [
		{ id: 0, name: 'Total de Empresas de Turismo', value: 2775 },
		{ id: 1, name: 'Empresas Registradas no Cadastur', value: 188 },
		{ id: 2, name: 'Serviços de Alimentação', value: 1693 },
		{ id: 3, name: 'Transporte Turístico', value: 377 },
		{ id: 4, name: 'Meios de Hospedagem', value: 230 },
		{ id: 5, name: 'Agências de Viagem', value: 207 },
		{ id: 6, name: 'Organizadores de Eventos', value: 160 },
		{ id: 7, name: 'Guias e Operadores de Turismo', value: 50 },
		{ id: 8, name: 'Acampamentos Turísticos', value: 46 },
		{ id: 9, name: 'Parques Temáticos', value: 12 },
	],
};

const touristicData: CityTouristicData[] = [
	{
		id: 1,
		name: CitiesENUM.VICOSA,
		images: [
			{ ...getCityImage(CitiesENUM.VICOSA, 0) },
			{ ...getCityImage(CitiesENUM.VICOSA, 1) },
			{ ...getCityImage(CitiesENUM.VICOSA, 2) },
			{ ...getCityImage(CitiesENUM.VICOSA, 3) },
		],
		companiesData: [
			{ id: 0, name: 'Total de Empresas de Turismo', value: 327 },
			{ id: 1, name: 'Empresas Registradas no Cadastur', value: 25 },
			{ id: 2, name: 'Serviços de Alimentação', value: 198 },
			{ id: 3, name: 'Transporte Turístico', value: 22 },
			{ id: 4, name: 'Meios de Hospedagem', value: 45 },
			{ id: 5, name: 'Agências de Viagem', value: 29 },
			{ id: 6, name: 'Organizadores de Eventos', value: 18 },
			{ id: 7, name: 'Guias e Operadores de Turismo', value: 8 },
			{ id: 8, name: 'Acampamentos Turísticos', value: 7 },
			{ id: 9, name: 'Parques Temáticos', value: 0 },
		],
	},
	{
		id: 2,
		name: CitiesENUM.TIANGUA,
		images: [
			{ ...getCityImage(CitiesENUM.TIANGUA, 0) },
			{ ...getCityImage(CitiesENUM.TIANGUA, 1) },
			{ ...getCityImage(CitiesENUM.TIANGUA, 2) },
			{ ...getCityImage(CitiesENUM.TIANGUA, 3) },
		],
		companiesData: [
			{ id: 0, name: 'Total de Empresas de Turismo', value: 819 },
			{ id: 1, name: 'Empresas Registradas no Cadastur', value: 22 },
			{ id: 2, name: 'Serviços de Alimentação', value: 474 },
			{ id: 3, name: 'Transporte Turístico', value: 155 },
			{ id: 4, name: 'Meios de Hospedagem', value: 51 },
			{ id: 5, name: 'Agências de Viagem', value: 53 },
			{ id: 6, name: 'Organizadores de Eventos', value: 48 },
			{ id: 7, name: 'Guias e Operadores de Turismo', value: 14 },
			{ id: 8, name: 'Acampamentos Turísticos', value: 19 },
			{ id: 9, name: 'Parques Temáticos', value: 5 },
		],
	},
	{
		id: 3,
		name: CitiesENUM.UBAJARA,
		images: [
			{ ...getCityImage(CitiesENUM.UBAJARA, 0) },
			{ ...getCityImage(CitiesENUM.UBAJARA, 1) },
			{ ...getCityImage(CitiesENUM.UBAJARA, 2) },
			{ ...getCityImage(CitiesENUM.UBAJARA, 3) },
		],
		companiesData: [
			{ id: 0, name: 'Total de Empresas de Turismo', value: 310 },
			{ id: 1, name: 'Empresas Registradas no Cadastur', value: 71 },
			{ id: 2, name: 'Serviços de Alimentação', value: 161 },
			{ id: 3, name: 'Transporte Turístico', value: 39 },
			{ id: 4, name: 'Meios de Hospedagem', value: 51 },
			{ id: 5, name: 'Agências de Viagem', value: 29 },
			{ id: 6, name: 'Organizadores de Eventos', value: 11 },
			{ id: 7, name: 'Guias e Operadores de Turismo', value: 10 },
			{ id: 8, name: 'Acampamentos Turísticos', value: 6 },
			{ id: 9, name: 'Parques Temáticos', value: 3 },
		],
	},
	{
		id: 4,
		name: CitiesENUM.IBIAPINA,
		images: [
			{ ...getCityImage(CitiesENUM.IBIAPINA, 0) },
			{ ...getCityImage(CitiesENUM.IBIAPINA, 1) },
			{ ...getCityImage(CitiesENUM.IBIAPINA, 2) },
			{ ...getCityImage(CitiesENUM.IBIAPINA, 3) },
		],
		companiesData: [
			{ id: 0, name: 'Total de Empresas de Turismo', value: 194 },
			{ id: 1, name: 'Empresas Registradas no Cadastur', value: 5 },
			{ id: 2, name: 'Serviços de Alimentação', value: 136 },
			{ id: 3, name: 'Transporte Turístico', value: 25 },
			{ id: 4, name: 'Meios de Hospedagem', value: 10 },
			{ id: 5, name: 'Agências de Viagem', value: 7 },
			{ id: 6, name: 'Organizadores de Eventos', value: 14 },
			{ id: 7, name: 'Guias e Operadores de Turismo', value: 0 },
			{ id: 8, name: 'Acampamentos Turísticos', value: 2 },
			{ id: 9, name: 'Parques Temáticos', value: 0 },
		],
	},
	{
		id: 5,
		name: CitiesENUM.SB,
		images: [
			{ ...getCityImage(CitiesENUM.SB, 0) },
			{ ...getCityImage(CitiesENUM.SB, 1) },
			{ ...getCityImage(CitiesENUM.SB, 2) },
			{ ...getCityImage(CitiesENUM.SB, 3) },
		],
		companiesData: [
			{ id: 0, name: 'Total de Empresas de Turismo', value: 339 },
			{ id: 1, name: 'Empresas Registradas no Cadastur', value: 12 },
			{ id: 2, name: 'Serviços de Alimentação', value: 220 },
			{ id: 3, name: 'Transporte Turístico', value: 55 },
			{ id: 4, name: 'Meios de Hospedagem', value: 18 },
			{ id: 5, name: 'Agências de Viagem', value: 24 },
			{ id: 6, name: 'Organizadores de Eventos', value: 19 },
			{ id: 7, name: 'Guias e Operadores de Turismo', value: 1 },
			{ id: 8, name: 'Acampamentos Turísticos', value: 2 },
			{ id: 9, name: 'Parques Temáticos', value: 0 },
		],
	},
	{
		id: 6,
		name: CitiesENUM.CARNAUBAL,
		images: [
			{ ...getCityImage(CitiesENUM.CARNAUBAL, 0) },
			{ ...getCityImage(CitiesENUM.CARNAUBAL, 1) },
			{ ...getCityImage(CitiesENUM.CARNAUBAL, 2) },
			{ ...getCityImage(CitiesENUM.CARNAUBAL, 3) },
		],
		companiesData: [
			{ id: 0, name: 'Total de Empresas de Turismo', value: 85 },
			{ id: 1, name: 'Empresas Registradas no Cadastur', value: 12 },
			{ id: 2, name: 'Serviços de Alimentação', value: 58 },
			{ id: 3, name: 'Transporte Turístico', value: 8 },
			{ id: 4, name: 'Meios de Hospedagem', value: 5 },
			{ id: 5, name: 'Agências de Viagem', value: 7 },
			{ id: 6, name: 'Organizadores de Eventos', value: 6 },
			{ id: 7, name: 'Guias e Operadores de Turismo', value: 0 },
			{ id: 8, name: 'Acampamentos Turísticos', value: 1 },
			{ id: 9, name: 'Parques Temáticos', value: 0 },
		],
	},
	{
		id: 7,
		name: CitiesENUM.GBA,
		images: [
			{ ...getCityImage(CitiesENUM.GBA, 0) },
			{ ...getCityImage(CitiesENUM.GBA, 1) },
			{ ...getCityImage(CitiesENUM.GBA, 2) },
			{ ...getCityImage(CitiesENUM.GBA, 3) },
		],
		companiesData: [
			{ id: 0, name: 'Total de Empresas de Turismo', value: 303 },
			{ id: 1, name: 'Empresas Registradas no Cadastur', value: 12 },
			{ id: 2, name: 'Serviços de Alimentação', value: 201 },
			{ id: 3, name: 'Transporte Turístico', value: 27 },
			{ id: 4, name: 'Meios de Hospedagem', value: 31 },
			{ id: 5, name: 'Agências de Viagem', value: 20 },
			{ id: 6, name: 'Organizadores de Eventos', value: 11 },
			{ id: 7, name: 'Guias e Operadores de Turismo', value: 4 },
			{ id: 8, name: 'Acampamentos Turísticos', value: 7 },
			{ id: 9, name: 'Parques Temáticos', value: 2 },
		],
	},
	{
		id: 8,
		name: CitiesENUM.CROATA,
		images: [
			{ ...getCityImage(CitiesENUM.CROATA, 0) },
			{ ...getCityImage(CitiesENUM.CROATA, 1) },
			{ ...getCityImage(CitiesENUM.CROATA, 2) },
			{ ...getCityImage(CitiesENUM.CROATA, 3) },
		],
		companiesData: [
			{ id: 0, name: 'Total de Empresas de Turismo', value: 104 },
			{ id: 1, name: 'Empresas Registradas no Cadastur', value: 17 },
			{ id: 2, name: 'Serviços de Alimentação', value: 57 },
			{ id: 3, name: 'Transporte Turístico', value: 14 },
			{ id: 4, name: 'Meios de Hospedagem', value: 5 },
			{ id: 5, name: 'Agências de Viagem', value: 10 },
			{ id: 6, name: 'Organizadores de Eventos', value: 13 },
			{ id: 7, name: 'Guias e Operadores de Turismo', value: 5 },
			{ id: 8, name: 'Acampamentos Turísticos', value: 0 },
			{ id: 9, name: 'Parques Temáticos', value: 0 },
		],
	},
	{
		id: 9,
		name: CitiesENUM.IPU,
		images: [
			{ ...getCityImage(CitiesENUM.IPU, 0) },
			{ ...getCityImage(CitiesENUM.IPU, 1) },
			{ ...getCityImage(CitiesENUM.IPU, 2) },
			{ ...getCityImage(CitiesENUM.IPU, 3) },
		],
		companiesData: [
			{ id: 0, name: 'Total de Empresas de Turismo', value: 294 },
			{ id: 1, name: 'Empresas Registradas no Cadastur', value: 12 },
			{ id: 2, name: 'Serviços de Alimentação', value: 188 },
			{ id: 3, name: 'Transporte Turístico', value: 32 },
			{ id: 4, name: 'Meios de Hospedagem', value: 14 },
			{ id: 5, name: 'Agências de Viagem', value: 28 },
			{ id: 6, name: 'Organizadores de Eventos', value: 20 },
			{ id: 7, name: 'Guias e Operadores de Turismo', value: 8 },
			{ id: 8, name: 'Acampamentos Turísticos', value: 2 },
			{ id: 9, name: 'Parques Temáticos', value: 2 },
		],
	},
];

export const getCityTouristicData = (city: string | undefined) => {
	return touristicData.find((item) => item.name === city) ?? defaultData;
};
