import { CityTouristicData } from '@/@types/city-touristic-data';
import { CitiesENUM, getCityImage } from '@/utils/get-city-image';

const defaultData: CityTouristicData = {
	id: -1,
	name: 'default',
	images: [{ ...getCityImage(false, CitiesENUM.UBAJARA) }],
	companiesData: {
		totalTourismCompanies: 2775,
		registeredCadasturCompanies: 188,
		foodServices: 1693,
		touristTransport: 377,
		lodging: 230,
		travelAgencies: 207,
		eventOrganizers: 160,
		tourGuidesAndOperators: 50,
		touristCamps: 46,
		themeParks: 12,
	},
};

const touristicData: CityTouristicData[] = [
	{
		id: 1,
		name: CitiesENUM.VICOSA,
		images: [{ ...getCityImage(false, CitiesENUM.VICOSA) }],
		companiesData: {
			totalTourismCompanies: 327,
			registeredCadasturCompanies: 25,
			foodServices: 198,
			touristTransport: 22,
			lodging: 45,
			travelAgencies: 29,
			eventOrganizers: 18,
			tourGuidesAndOperators: 8,
			touristCamps: 7,
			themeParks: 0,
		},
	},
	{
		id: 2,
		name: CitiesENUM.TIANGUA,
		images: [{ ...getCityImage(false, CitiesENUM.TIANGUA) }],
		companiesData: {
			totalTourismCompanies: 819,
			registeredCadasturCompanies: 22,
			foodServices: 474,
			touristTransport: 155,
			lodging: 51,
			travelAgencies: 53,
			eventOrganizers: 48,
			tourGuidesAndOperators: 14,
			touristCamps: 19,
			themeParks: 5,
		},
	},
	{
		id: 3,
		name: CitiesENUM.UBAJARA,
		images: [{ ...getCityImage(false, CitiesENUM.UBAJARA) }],
		companiesData: {
			totalTourismCompanies: 310,
			registeredCadasturCompanies: 71,
			foodServices: 161,
			touristTransport: 39,
			lodging: 51,
			travelAgencies: 29,
			eventOrganizers: 11,
			tourGuidesAndOperators: 10,
			touristCamps: 6,
			themeParks: 3,
		},
	},
	{
		id: 4,
		name: CitiesENUM.IBIAPINA,
		images: [{ ...getCityImage(false, CitiesENUM.IBIAPINA) }],
		companiesData: {
			totalTourismCompanies: 194,
			registeredCadasturCompanies: 5,
			foodServices: 136,
			touristTransport: 25,
			lodging: 10,
			travelAgencies: 7,
			eventOrganizers: 14,
			tourGuidesAndOperators: 0,
			touristCamps: 2,
			themeParks: 0,
		},
	},
	{
		id: 5,
		name: CitiesENUM.SB,
		images: [{ ...getCityImage(false, CitiesENUM.SB) }],
		companiesData: {
			totalTourismCompanies: 339,
			registeredCadasturCompanies: 12,
			foodServices: 220,
			touristTransport: 55,
			lodging: 18,
			travelAgencies: 24,
			eventOrganizers: 19,
			tourGuidesAndOperators: 1,
			touristCamps: 2,
			themeParks: 0,
		},
	},
	{
		id: 6,
		name: CitiesENUM.CARNAUBAL,
		images: [{ ...getCityImage(false, CitiesENUM.CARNAUBAL) }],
		companiesData: {
			totalTourismCompanies: 85,
			registeredCadasturCompanies: 12,
			foodServices: 58,
			touristTransport: 8,
			lodging: 5,
			travelAgencies: 7,
			eventOrganizers: 6,
			tourGuidesAndOperators: 0,
			touristCamps: 1,
			themeParks: 0,
		},
	},
	{
		id: 7,
		name: CitiesENUM.GBA,
		images: [{ ...getCityImage(false, CitiesENUM.GBA) }],
		companiesData: {
			totalTourismCompanies: 303,
			registeredCadasturCompanies: 12,
			foodServices: 201,
			touristTransport: 27,
			lodging: 31,
			travelAgencies: 20,
			eventOrganizers: 11,
			tourGuidesAndOperators: 4,
			touristCamps: 7,
			themeParks: 2,
		},
	},
	{
		id: 8,
		name: CitiesENUM.CROATA,
		images: [{ ...getCityImage(false, CitiesENUM.CROATA) }],
		companiesData: {
			totalTourismCompanies: 104,
			registeredCadasturCompanies: 17,
			foodServices: 57,
			touristTransport: 14,
			lodging: 5,
			travelAgencies: 10,
			eventOrganizers: 13,
			tourGuidesAndOperators: 5,
			touristCamps: 0,
			themeParks: 0,
		},
	},
	{
		id: 9,
		name: CitiesENUM.IPU,
		images: [
			{ ...getCityImage(false, CitiesENUM.IPU) },
			{ ...getCityImage(false, CitiesENUM.GBA) },
		],
		companiesData: {
			totalTourismCompanies: 294,
			registeredCadasturCompanies: 12,
			foodServices: 188,
			touristTransport: 32,
			lodging: 14,
			travelAgencies: 28,
			eventOrganizers: 20,
			tourGuidesAndOperators: 8,
			touristCamps: 2,
			themeParks: 2,
		},
	},
];

export const getCityTouristicData = (city: string | undefined) => {
	return touristicData.find((item) => item.name === city) ?? defaultData;
};
